### ISSUE TITLE
Filter by exact date

### ISSUE THREAD

**Issue by madewild** [madewild/CAMille#30]
input field with calendar (from - to)

**Comment by madewild** [comment]
implemented in dev
interaction with other filters is tricky so I may have forgotten something... @anjacque could you test different combinations of filters including exact date in order to confirm everything is ok?

**Comment by anjacque** [comment]
It seems to work properly! Two things if we want to improve it even more:
1) We could make impossible to enter "impossible requests" in combination with other filters (for example, when the "Exact date" filter does not fit the years selected in the "Year Filter"). For now, it only shows "Aucun résultat". Could the different filters work in a dynamic way?
2) The drop-down menu for the year selection is not really practical to use because we have a large range of years. I don't know what to propose to fix it, except if we have a box to fill by entering a year manually. To be discussed.

**Comment by madewild** [comment]
Not impossible but I would keep for later, I created issue #49. Closing now.
