### ISSUE TITLE
Filter by multiple newspapers

### ISSUE THREAD

**Issue by madewild** [madewild/CAMille#36]
Currently only possible one by one (newseye style), to replace by checkboxes or multiselect?

**Comment by madewild** [comment]
use checkboxes like on cibleplus?

**Comment by madewild** [comment]
Implemented in dev with a dropdown. A bit less sexy than the simple list, but the functionality is there (css can be improved later).
You can now (un)select multiple newspapers with the CTRL key (command key on Mac). This should play nicely with other filters.
@anjacque could you test before I replicate for months and days of the week ?

**Comment by madewild** [comment]
New test with checkboxes: https://dev.camille-ulb-kbr.be/?query=*&sortcrit=relevance&paper=JB421&paper=JB555&paper=JB567

**Comment by anjacque** [comment]
This is really nice, now: thanks for your tenacity! :-)
An idea to be discussed later: we could add a "(Un)Select all" button, which could allow to go faster if the user only wants to (un)select one or two newspaper(s) (the same could be done for other filters with checkboxes). But this "(Un)Select all" button should work without activating the filter, otherwise it could be problematic.

**Comment by madewild** [comment]
Added in #50, closing now.
